title:            Jasen Qin
tagline:          'Is it possible for things to just work?'
description:      'It could be possible for things to just work'
baseurl:          '/'
paginate:         5

author:
  name:           'Jasen Qin'

plugins:
  - jekyll-paginate
  - jekyll-gist

version:          3.0.0
