# Setup
title:            Eletei
tagline:          'The enlightened site'
description:      'Made by yours truly. </br></br>Fact: The world truly sucks.</br></br>'
baseurl:          '/'
paginate:         5 # display 5 posts at first. Then scroll down to load more posts (aka pages)

# About and contact
author:
  name:           'Jason Qin'

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
