// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  main: [
    { type: 'autogenerated', dirName: 'base' }
  ],
  research: [
    { type: 'autogenerated', dirName: 'research' }
  ],
  about: [
    { type: 'autogenerated', dirName: 'about' }
  ],
};

module.exports = sidebars;
